---

roles:
- name: weareinteractive.sudo
  path: vendor/roles
  src: https://github.com/weareinteractive/ansible-sudo.git
  version: 1.14.1

- name: ansible.users
  path: vendor/roles
  src: https://github.com/unxnn/ansible-role-users.git
  version: v1.0.4

- name: geerlingguy.docker
  path: vendor/roles
  src: https://github.com/geerlingguy/ansible-role-docker.git
  version: 4.1.1

- name: geerlingguy.helm
  path: vendor/roles
  src: https://github.com/geerlingguy/ansible-role-helm.git
  version: 1.0.0

collections:
- name: kubernetes.core
  path: collections
  src: https://github.com/ansible-collections/kubernetes.core.git
  version: 2.2.1
