---

- name: Upgrade all installed packages for Debian and Ubuntu
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: install pip3
  apt:
    name: python3-pip
    state: present

- name: Install kubernetes python package
  pip:
    name: kubernetes
  when: inventory_hostname in groups['k3s_master']
