---

- name: Add bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy Nginx ingress Controller
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: bitnami/nginx
    release_namespace: default
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
